"""tools/cut_finetune_arms.py -- the minimal-fine-tuning ablation ladder, generated and verified.

Kaelin 2026-10-08: "figure out what the absolute minimum amount of fine-tuning required is" to move the
882k release model to a new board, and show VRAM / training steps / accuracy / wall time side by side,
to judge whether it is doable on consumer hardware, on-device.

Every arm is the SAME fine-tune recipe (configs/ft_base_dict6x6.yaml: the zero-shot transfer config +
a short fresh schedule) and differs ONLY in cfg["finetune"]["lr_mult"] (which parameters train, and at
what fraction of the base LR) and optionally cfg["finetune"]["reinit"]. The flat-key diff of every arm
against the base, and of the base against configs/transfer_dict6x6.yaml, is computed and asserted here
and written into each file's header -- the ablation one-key rule, applied to a block.

Generated by yaml round-trip, so the base's comments are not carried: read configs/transfer_dict6x6.yaml
(and its own header chain) for the generator / training rationale.
"""
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from dcc.trainutil import flat_cfg

SRC = "configs/transfer_dict6x6.yaml"
BASE = "configs/ft_base_dict6x6.yaml"
FROM = "runs/rel_w882_c2_100k_rev6/ckpt_0100000.pt"

# Short fresh schedule. 5,000 steps at batch 16 x accum 2 (160k samples, 1/20 of the release budget);
# val every 250 steps on 1,000 samples so steps-to-target is resolved to 250; EMA 0.99 (time constant
# 100 steps) instead of 0.999 so the validated weights do not lag the live ones by a fifth of the run;
# a fresh generator stream (train_seed 2100) so the fine-tune never replays the pretraining's samples.
BASE_OVERRIDES = {
    ("train", "steps"): 5000, ("train", "warmup_steps"): 100, ("train", "val_every"): 250,
    ("train", "val_subset"): 1000, ("train", "full_val_every"): 5000, ("train", "ema_decay"): 0.99,
    ("train", "ckpt_rolling_every"): 1000, ("train", "early_stop", "enabled"): False,
    ("train", "wandb", "enabled"): False, ("synth", "train_seed"): 2100,
    ("finetune", "from"): FROM,
}

# Layer-wise LR decay for the whole-model arm: gamma per stage, counted from the heads inward.
LLRD_GAMMA = 0.3
LLRD_DEPTH = {"cls": 0, "hm": 0, "d1": 1, "d2": 2, "d3": 3, "gate3": 3, "blocks": 4, "norm": 4,
              "e4": 5, "e3": 6, "e2": 7, "e1": 8}
ALL = ["e1", "e2", "e3", "e4", "blocks", "norm", "gate3", "d3", "d2", "d1", "hm", "cls"]

ARMS = {
    # ---- Kaelin's four ----
    "ft01_head": (
        {"cls.*": 1.0}, [],
        "1. Only the ID head unfrozen (37,968 params, 4.3%). The minimum conceivable: identity is the only board-specific part by design (freeze_trunk boundary)."),
    "ft02_head_bneck_hm_lr0p1": (
        {"cls.*": 1.0, "blocks.*": 0.1, "norm.*": 0.1, "hm.*": 0.1}, [],
        "2. ID head + attention bottleneck + corner head unfrozen, the pretrained parts at LOW LR (0.1x); the head at 1x since it must relearn identity. Tests whether board-scale context (the bottleneck) must adapt to new markers."),
    "ft03_head_bneck_lr0p01_hm_lr0p1": (
        {"cls.*": 1.0, "blocks.*": 0.01, "norm.*": 0.01, "hm.*": 0.1}, [],
        "3. As 2, bottleneck at an EXTREMELY reduced LR (0.01x = 3e-6). Is a nudge to attention enough, or does it need real movement?"),
    "ft04_full_llrd0p3": (
        {f"{m}.*": round(LLRD_GAMMA ** LLRD_DEPTH[m], 6) for m in ALL}, [],
        f"4. Whole model unfrozen with layer-wise LR decay, gamma={LLRD_GAMMA} per stage from the heads inward (e1 at {LLRD_GAMMA**8:.1e}x -- effectively frozen). The 'let everything move a little, early layers almost not at all' recipe."),
    # ---- suggested additions ----
    "ft05_head_gate3": (
        {"cls.*": 1.0, "gate3.*": 1.0}, [],
        "5. ID head + the H/4 attention gate (6,209 params). The gate chooses which skip features reach the class rung; cheapest possible lever above the head alone."),
    "ft06_head_d3_lr0p1": (
        {"cls.*": 1.0, "d3.*": 0.1}, [],
        "6. ID head + the H/4 decoder rung it taps (110,720 params, 0.1x). Tests whether identity needs the feature MIXER to adapt rather than the bottleneck."),
    "ft07_head_reinit": (
        {"cls.*": 1.0}, ["cls.*"],
        "7. As 1 but the class head is RE-INITIALISED instead of warm-started from the old board's head (13.4% raw agreement on the new board, above chance). Does the old head help or hinder?"),
    "ft08_bitfit": (
        {"cls.*": 1.0, "*.bias": 1.0, "blocks.*.n1.weight": 1.0, "blocks.*.n2.weight": 1.0, "norm.weight": 1.0}, [],
        "8. BitFit: ID head + every bias in the network + the LayerNorm scales (3,666 bias + 768 LN-scale params; no weight matrix moves). Classic parameter-efficient fine-tuning, the transformer variant; the smallest optimizer state of any arm that touches the trunk. LN scales are included because PyTorch's fused LayerNorm backward raises on a bias-only-trainable LayerNorm (NativeLayerNormBackward0 'invalid gradient at index 2'), measured 2026-10-08."),
    "ft09_full_lr0p1": (
        {m + ".*": 0.1 for m in ALL} | {"cls.*": 1.0}, [],
        "9. Whole model at a UNIFORM low LR (0.1x), head at 1x. The naive full fine-tune; comparator for the layer-decayed arm 4."),
    "ft10_full_lr1": (
        {m + ".*": 1.0 for m in ALL}, [],
        "10. Whole model at the full pretraining LR. The upper reference: what 5,000 steps of unconstrained training buys, and whether it damages localisation."),
    # ---- round 2, cut after watching round 1 (2026-10-08 09:26): head-only sat at 56% ID at step 2500 and was
    # still climbing ~0.3 pp per 250 steps, so the question "can the head alone EVER get there" needs more LR
    # and more steps, not a verdict at 5k. Optional 4th element: train-block overrides for this arm only.
    "ft11_head_lr3x": (
        {"cls.*": 3.0}, [],
        "11. Only the ID head, at 3x the base LR (9e-4 peak). Is head-only slow because the head is starved of LR?", {}),
    "ft12_head_20k": (
        {"cls.*": 1.0}, [],
        "12. Only the ID head, 20,000 steps (4x the ladder budget; val every 500). Where does head-only saturate when given time?",
        {("train", "steps"): 20000, ("train", "val_every"): 500, ("train", "full_val_every"): 20000}),
    # Cut 2026-10-08 10:12 after arms 1-2 finished: head-only plateaued at 57% (5k AND flat), head+bottleneck+hm
    # at 0.1x reached 90.5% and was still climbing ~0.3 pp / 250 steps. The minimal PARAMETER set that can work is
    # arm 2's; what remains is whether it is LR- or budget-limited.
    "ft13_head_bneck_hm_lr0p1_20k": (
        {"cls.*": 1.0, "blocks.*": 0.1, "norm.*": 0.1, "hm.*": 0.1}, [],
        "13. Arm 2's recipe for 20,000 steps (val every 500). Does the bottleneck-at-0.1x recipe reach the trained-board ceiling given time?",
        {("train", "steps"): 20000, ("train", "val_every"): 500, ("train", "full_val_every"): 20000}),
    "ft14_head_bneck_hm_lr1": (
        {"cls.*": 1.0, "blocks.*": 1.0, "norm.*": 1.0, "hm.*": 1.0}, [],
        "14. Arm 2's parameter set at the FULL base LR, 5,000 steps. Is arm 2 slow because 0.1x starves the bottleneck?", {}),
    # Kaelin 2026-10-08 10:50, after arms 1-4: "maybe we need to allow for more of a retrain of the bottleneck?"
    # A bottleneck-LR ladder with everything else held at arm 2's values: 0.01x (arm 3), 0.1x (arm 2), 0.3x, 1x.
    "ft15_head_bneck_lr0p3_hm_lr0p1": (
        {"cls.*": 1.0, "blocks.*": 0.3, "norm.*": 0.3, "hm.*": 0.1}, [],
        "15. Arm 2 with the bottleneck at 0.3x (corner head still 0.1x): the bottleneck-LR ladder's third rung.", {}),
    # Kaelin 2026-10-08 17:00: "take the 25k model, freeze everything before the bottleneck (inclusive of the
    # bottleneck) and try train it to be good at one specific board? the theory is that the general pretrain will
    # have taught it to extract general features". Cut with --from-ckpt runs/mb15_base_50k/ckpt_0025000.pt
    # --prefix mb15_ for the test, and from the 882k release (default) as the control with the same trainable set.
    "ft17_post_bneck": (
        {"gate3.*": 1.0, "d3.*": 1.0, "d2.*": 1.0, "d1.*": 1.0, "hm.*": 1.0, "cls.*": 1.0}, [],
        "17. Everything AFTER the bottleneck trains at the base LR (gate, three decoder rungs, both heads: 191,890 params); encoder and bottleneck frozen.", {}),
    # Cut 2026-10-08 17:35 after the bottleneck-LR ladder closed monotone (0.01x 69%, 0.1x 90%, 0.3x 93%, 1x 97%)
    # with the whole model at 1x at 98.4%: is the bottleneck still rate-limited above 1x, and does the next
    # module inward (e4, 221,696 params) close the gap to the whole model?
    "ft18_head_bneck_lr3x_hm_lr0p1": (
        {"cls.*": 1.0, "blocks.*": 3.0, "norm.*": 3.0, "hm.*": 0.1}, [],
        "18. Arm 16 with the bottleneck at 3x the base LR (9e-4). Is 1x the ceiling for the bottleneck, or is it still rate-limited?", {}),
    "ft19_head_bneck_e4_hm_lr1": (
        {"cls.*": 1.0, "blocks.*": 1.0, "norm.*": 1.0, "e4.*": 1.0, "hm.*": 1.0}, [],
        "19. Arm 14 plus the deepest encoder stage e4 at 1x (658,801 params trainable). Does the next module inward close the 1.3 pp gap to the whole model?", {}),
    # Cut 2026-10-08 21:05 after arm 18 (bottleneck 3x) matched the whole model at 1x: bounds the ceiling.
    "ft20_full_lr3x": (
        {m + ".*": 3.0 for m in ALL}, [],
        "20. Whole model at 3x the base LR (9e-4). The upper bound once the bottleneck proved still rate-limited at 1x.", {}),
    # Kaelin 2026-10-08 21:40: "is achieving full accuracy possible with fine tuning?" The 5k arms flatten at 98.2%
    # with the LR at its floor; the pretrain itself took 17.5k steps to pass 99% and 70k to pass 99.5%. The best
    # recipe (arm 18) on a 20k budget is the direct test.
    "ft21_head_bneck_lr3x_hm_lr0p1_20k": (
        {"cls.*": 1.0, "blocks.*": 3.0, "norm.*": 3.0, "hm.*": 0.1}, [],
        "21. Arm 18 (bottleneck at 3x) for 20,000 steps (val every 500): does the minimal recipe reach the trained-board 99.5% given budget?",
        {("train", "steps"): 20000, ("train", "val_every"): 500, ("train", "full_val_every"): 20000}),
    "ft16_head_bneck_lr1_hm_lr0p1": (
        {"cls.*": 1.0, "blocks.*": 1.0, "norm.*": 1.0, "hm.*": 0.1}, [],
        "16. Arm 2 with the bottleneck at the FULL base LR (corner head still 0.1x): the ladder's top rung; vs arm 14 isolates the corner head's LR.", {}),
}


def _set(d, path, value):
    for k in path[:-1]:
        d = d.setdefault(k, {})
    d[path[-1]] = value


def _dump(cfg, out, header):
    Path(out).write_text("\n".join("# " + ln if ln else "#" for ln in header.split("\n")) + "\n"
                         + yaml.safe_dump(cfg, sort_keys=False, width=110))


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--from-ckpt", default=FROM, help="checkpoint every arm fine-tunes from")
    ap.add_argument("--prefix", default="", help="config/run-name prefix, e.g. mb_ to cut the ladder against the multi-board base")
    ap.add_argument("--arms", nargs="+", default=list(ARMS), choices=list(ARMS), help="subset of arms to cut")
    a = ap.parse_args()
    base_path = f"configs/{a.prefix}ft_base_dict6x6.yaml" if a.prefix else BASE
    src = yaml.safe_load(Path(SRC).read_text())
    base = yaml.safe_load(Path(SRC).read_text())
    for path, v in {**BASE_OVERRIDES, ("finetune", "from"): a.from_ckpt}.items():
        _set(base, path, v)
    diff = {k: (flat_cfg(src).get(k), flat_cfg(base).get(k)) for k in set(flat_cfg(src)) | set(flat_cfg(base))
            if flat_cfg(src).get(k) != flat_cfg(base).get(k)}
    assert set(diff) == {".".join(p) for p in BASE_OVERRIDES}, diff
    _dump(base, base_path, f"FINE-TUNE BASE, generated by tools/cut_finetune_arms.py from {SRC} -- do not hand-edit; regenerate.\n"
          f"Differs from {SRC} in EXACTLY these keys (verified at cut time):\n" +
          "\n".join(f"  {k}: {a!r} -> {b!r}" for k, (a, b) in sorted(diff.items())) +
          "\nNot trainable by itself: arms add finetune.lr_mult (and optionally finetune.reinit).")
    print(f"-> {base_path}  ({len(diff)} keys vs {SRC})")
    for name, (lr_mult, reinit, note, *rest) in ((n, ARMS[n]) for n in a.arms):
        overrides = rest[0] if rest else {}
        arm = yaml.safe_load(Path(base_path).read_text())
        arm["finetune"]["lr_mult"] = lr_mult
        if reinit:
            arm["finetune"]["reinit"] = reinit
        for path, v in overrides.items():
            _set(arm, path, v)
        d = {k for k in set(flat_cfg(arm)) | set(flat_cfg(base)) if flat_cfg(arm).get(k) != flat_cfg(base).get(k)}
        allowed = {".".join(p) for p in overrides} | {"finetune.reinit"}
        assert all(k.startswith("finetune.lr_mult.") or k in allowed for k in d), (name, d)
        out = f"configs/{a.prefix}{name}.yaml"
        _dump(arm, out, f"MINIMAL-FINE-TUNING ARM, generated by tools/cut_finetune_arms.py from {base_path} -- do not hand-edit; regenerate.\n"
              f"{note}\nDiffers from the base ONLY in: {sorted(d)}")
        print(f"-> {out}  trainable: {list(lr_mult)}{' reinit ' + str(reinit) if reinit else ''}")


if __name__ == "__main__":
    main()
