"""tools/cut_multiboard.py -- the multi-board pretraining base and its per-board evaluation configs.

Kaelin 2026-10-08: "training the main model from scratch on a larger set of boards (say 15 different boards)".
Hypothesis: a trunk + class head trained to read identity across many marker families learns a board-GENERIC
identity read, so moving to a new board afterwards needs far less (ideally head-only) fine-tuning than the
single-board 882k release does -- which the ladder in 28_finetune_minimal measured at >50% of the network.

configs/mb15_base.yaml = the 882k release recipe (configs/abl_c2_wh_clsfocal_lam2.yaml) + board.pool of 15 boards
drawn uniformly per sample (dcc/synth.py:_composite_board) + a 50k-step budget (the ablation budget, not the 100k
release budget). The ENTIRE OpenCV DICT_6X6 family is held out, so the transfer target DICT_6X6_250 stays unseen,
and DICT_ARUCO_ORIGINAL is held out as a second unseen family. The original board (DICT_5X5_50 ids 0-11) is in the
pool as DICT_5X5_1000 offset 0 -- byte-identical markers, asserted below.

Also cuts one single-board eval config per pool entry (configs/mb15_eval_<dict>_<offset>.yaml) so
tools/eval_checkpoint.py can score the base per board.
"""
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from dcc.trainutil import flat_cfg

SRC = "configs/abl_c2_wh_clsfocal_lam2.yaml"
OUT = "configs/mb15_base.yaml"
POOL = [{"dictionary": d, "marker_id_offset": off}
        for d in ["DICT_4X4_1000", "DICT_5X5_1000", "DICT_7X7_1000", "DICT_APRILTAG_16h5", "DICT_APRILTAG_25h9",
                  "DICT_APRILTAG_36h10", "DICT_APRILTAG_36h11"] for off in (0, 12)] + \
       [{"dictionary": "DICT_ARUCO_MIP_36h12", "marker_id_offset": 0}]
HELD_OUT = ["DICT_6X6_* (the transfer target family)", "DICT_ARUCO_ORIGINAL"]
OVERRIDES = {("train", "steps"): 50000, ("train", "val_every"): 2500, ("train", "full_val_every"): 25000,
             ("train", "early_stop", "enabled"): False, ("train", "wandb", "enabled"): False}


def _set(d, path, v):
    for k in path[:-1]:
        d = d.setdefault(k, {})
    d[path[-1]] = v


def _header(lines):
    return "\n".join("# " + ln if ln else "#" for ln in lines) + "\n"


def main():
    import argparse
    import cv2
    import numpy as np
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--boards", default=None, help="comma list of DICT:offset to use instead of the 15-board pool, e.g. "
                    "DICT_5X5_1000:0,DICT_4X4_1000:0,DICT_APRILTAG_36h11:0 (the 3-family reduced test)")
    ap.add_argument("--steps", type=int, default=OVERRIDES[("train", "steps")])
    ap.add_argument("--name", default="mb15", help="config stem: configs/<name>_base.yaml and configs/<name>_eval_*.yaml")
    a = ap.parse_args()
    global POOL, OUT
    if a.boards:
        POOL = [{"dictionary": d, "marker_id_offset": int(o)} for d, o in (b.split(":") for b in a.boards.split(","))]
    OVERRIDES[("train", "steps")] = a.steps
    OUT = f"configs/{a.name}_base.yaml"
    d50 = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_50).bytesList
    d1000 = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_5X5_1000).bytesList
    assert np.array_equal(d50[:12], d1000[:12]), "DICT_5X5_1000 offset 0 is not the original board"
    assert a.boards or len(POOL) == 15
    src = yaml.safe_load(Path(SRC).read_text())
    cfg = yaml.safe_load(Path(SRC).read_text())
    cfg["board"]["pool"] = POOL
    for path, v in OVERRIDES.items():
        _set(cfg, path, v)
    fs, fc = flat_cfg(src), flat_cfg(cfg)
    diff = sorted(k for k in set(fs) | set(fc) if fs.get(k) != fc.get(k))
    assert all(k.startswith("board.pool") or k in {".".join(p) for p in OVERRIDES} for k in diff), diff
    Path(OUT).write_text(_header([
        f"MULTI-BOARD PRETRAINING BASE, generated by tools/cut_multiboard.py from {SRC} -- do not hand-edit; regenerate.",
        f"{len(POOL)} boards drawn uniformly per sample (board.pool); held out: " + ", ".join(HELD_OUT) + ".",
        f"Differs from {SRC} ONLY in board.pool.* and: " + ", ".join(".".join(p) for p in OVERRIDES) + "."]) + yaml.safe_dump(cfg, sort_keys=False, width=110))
    print(f"-> {OUT}  ({len(POOL)} boards, {len(diff)} flat keys vs {SRC})")
    for b in POOL:
        e = yaml.safe_load(Path(SRC).read_text())
        e["board"].update(b)
        name = f"configs/{a.name}_eval_{b['dictionary'].replace('DICT_', '')}_{b['marker_id_offset']}.yaml"
        Path(name).write_text(_header([f"PER-BOARD EVAL CONFIG for the multi-board base, generated by tools/cut_multiboard.py from {SRC}.",
                                       f"board.dictionary={b['dictionary']} board.marker_id_offset={b['marker_id_offset']}; nothing else differs."])
                              + yaml.safe_dump(e, sort_keys=False, width=110))
    print(f"-> {len(POOL)} per-board eval configs configs/{a.name}_eval_*.yaml")


if __name__ == "__main__":
    main()
